<?php
    //Variable avec le titre de la page
    $title = "Travaux et publications";
    //Appel template header
    require_once('./templates/header.php');
    ?>

<br>
        <br>
        <section>
            <div class="container">
                    <div class="row">
                        <div class="title col-12">
                            <h2>Travaux et Publications</h2>
                        </div>
                    </div>
            <br>
            <div class="container">
                <div class="row">
                <div class="col-lg-12 mx-auto">
                        <h3>La Version de Ève ou l’élaboration d’un mythe anarchiste(Acte1: La déconstruction du mythe hiérarchique)</h3>
                    </div>
                    <div class="col-lg-12">
                        <img src="" alt="">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <p>
                        

Comme il y est question d’anthropologie anarchiste, il paraissait judicieux d’en offrir un état des lieux, une esquisse, pour le moins une axiomatique, sinon quelques prémisses. Cependant, au fur et mesure que s’établissent les primats anarchistes, on s’aperçoit de l’importance croissance que prend le mythe, et ce jusqu’à l’extrême assertion que représente la nécessité de son élaboration. Or si l’on admet que la Genèse est le mythe masculin de la hiérarchie, alors le mythe anarchiste se doit être féminin et en ce sens, il ne peut-être que celui du « Matriarcat ». 
Mythique matriarcat
S’il existe bien peu de sociétés humaines où le matriarcat nous soit parvenu comme tel ou encore que son sens étymologique face débat, l’existence d’un tel système social pourrait avoir été de mise durant la préhistoire. Ce qui pose alors question est de savoir pourquoi et comment le patriarcat s’y serait substitué pour s’imposer entre 5000 et 3000 ans avant notre ère. 
Partant du culte de la « Déesse Mère », certains chercheurs à la suite des travaux de l’archéologue Marija Gimbutas avancent que le patriarcat se serait substitué à ce matriarcat prépondérant dans les sociétés de cueillette et de chasse puis dans celles d’élevage, depuis les sociétés pastorales de nomades d’Eurasie. Cette hypothèse qui assimile la culture des kourganes à l’habitat originel des Indo-Européens, part du présupposé que cette population serait proto-indo-européenne et qu’elle parlerait la langue mère de toutes les langues indo-européennes. Quand elles commencèrent à se disperser, ces tribus connaissaient déjà la métallurgie du cuivre et comptaient parmi les plus anciens éleveurs de chevaux du monde. Arguant du fait que cette culture du mésolithique située entre la Volga et les fleuves de l’Oural se distinguait par la domestication précoce du cheval, Marija Gimbutas affirme que la naissance du système patriarcal est consubstantielle de la domestication du cheval chez les populations indo-européennes des Kourganes. 
Dès lors se pose la question de savoir comment la domestication du cheval a t’elle pu donner naissance au système patriarcal chez les populations indo-européennes des Kourganes? On peut d’emblée adhérer à l’hypothèse que c’est la mobilité ainsi gagnée qui aurait créé des groupes de cavaliers combattants. Ce faisant, les tribus patriarcales des kourganes auraient, en migrant vers l’Europe, imposé aux populations matriarcales indigènes un système hiérarchique guerrier qui aurait conduit à des formes de société dites patriarcales. Ils auraient transformé la culture de type agricole existante et se seraient établis en tant qu’aristocratie dirigeante, imposant leur langue. Mais les études historiques tendent à montrer que malgré leur maîtrise du cheval et notamment grâce à leurs chars de combat1, cette supériorité n’était pas réellement décisive face à des adversaires suffisamment organisés ou puissants.
On peut aussi considérer comme nous l’avons fait analogiquement que depuis la domestication du cheval, l’homme s’est lui-même converti en étalon, mâle reproducteur du haras. Mais on peut également filer un plus la métaphore. Le mot « haras », dont l’étymologie est probablement issue du vieux norrois harr « gris », tire son origine de la couleur la plus fréquente de la robe des chevaux. On sait également que les premières castes aristocratiques étaient des castes de cavaliers. Si Buffon ne s’y est pas trompé et que le cheval est la plus noble conquête de l’homme, alors le cheval à quelque chose à voir avec la noblesse. On peut d’ailleurs imaginer que cette noblesse, si elle est étymologiquement liée à la connaissance, est celle de la domestication du cheval. Mais la domestication ce fier et fougueux animal qui partage avec lui les fatigues des guerres et la gloire des combats est aussi l’avènement de la conquête.
Si en occident, la noblesse de robe supplanta une noblesse d’épée qui était celle de la cavalerie, alors nul doute que la noblesse est celle d’une robe qui fut aussi celle d’un cheval. Mais que cette robe soit celle de leur monture ou celle de leur charge, il n’y a guère d’illusion à se faire sur la noblesse de nos aristocrates. Sachant que le mot robe n’est que le déverbal de l’ancien français rober qui ne signifie rien d’autre que « voler » et qui ne subsiste plus en français moderne que sous la forme préfixée « dérober ». Sachant aussi que ce mot a eu pour sens « butin de guerre », « dépouille » puis, par spécialisation, « tunique » et enfin, par hyperspécialisation, « vêtement féminin », on peut aussi commencer à se demander avec anxiété ce qui a réellement été dérobé? 
Se demander ce qui servait effectivement de butin de guerre ou plus justement, ce qu’était réellement ce butin? Se demander si ce dérobement féminin n’était pas plutôt « détroussage » de femmes. Celle d’une pratique qui consisterait pour les peuples antiques ou tribaux à « prendre [enlever] pour épouses » les femmes de leurs voisins2 et dont l’abductio romain, ce rapt de la fiancée dans la demeure de ses parents par le futur marié, ne serait que la  ritualisation. 
1. La fin de la prééminence féminine
Mais à partir de là on peut également opposer une hypothèse complémentaire à celle avancée par Marija Gimbutas sur la naissance du système patriarcal chez les populations indo-européennes des Kourganes. S’il nous a été dit que cette genèse du patriarcat s’est effectuée en concomitance avec la « domestication du cheval », il nous a également été stipulé que ces mêmes populations connaissaient déjà la « métallurgie du cuivre ». 
1.1 Le « vit de père » ou la reconnaissance du rôle masculin dans la procréation
Dès lors nous émettons l’hypothèse que c’est à partir du commerce de la métallurgie du cuivre comme analogique de l’échange des femmes que s’est établi le système patriarcal et ce dérobement du féminin. Mais comment s’est effectuée cette appropriation est toute la question qui nous obsède. Comment sinon arriver à comprendre cette énigmatique phrase de la Genèse une fois que Ève et Adam eurent goûté du fruit défendu: « alors, leurs yeux à tous deux s’ouvrirent et ils connurent qu’ils étaient nus »? 
Comment, en effet, nos ancêtres n’auraient pu se rendre compte qu’ils vivaient nus sinon en admettant que, mythologiquement, ils vivaient dans l’ignorance de la distinction des sexes ou de leur fonction? Comment entendre sinon cette étymologie du mot « sexe », de ce sexus latin, de seco « couper » dont le sens originel pourrait être « division [du genre humain] »? Le seul pêché qu’ait vraiment commis Ève en mordant la pomme n’est certainement pas celui d’avoir goûté au fruit défendu mais simplement d’avoir ouvert la bouche. Ouvert la bouche et prononcé un mot qui fût inversé à mal. Non pas de ce malum « pomme3 » mais de malus « mal » qui fut en fait un « mâle », qui fut fait mâle. 
Dit plus simplement, si ce jour-là Ève goûta pour la première fois du fruit défendu, entendu comme « péché de chair », c’est qu’auparavant elle ignorait qu’Adam était un homme, comme lui-même et comme toutes les créatures de Dieu d’ailleurs ; de toute, à l’exception notable du nachash. S’il est impossible zoologiquement d’affilier à une espèce particulière le serpent qui influença Ève en ce funeste jour, sémantiquement ce reptile ne pouvait être qu’une « vipère ». Une vipère non pas pour la perfidie de ses conseils, mais bien parce que ce jour-là Ève vit Père, sinon le vit de père. Plus exactement la naissance d’un être dont la reconnaissance en paternité en quelque sorte avérée, avait fait de lui ce qu’il advint, un « homme ». 
Au commencement, le fruit de l’arbre de la connaissance du bien et du mal était peut-être une « pomme » si on considère ce fruit comme malum, mais bien plus sûrement encore cette connaissance n’était pas celle du « mal » mais bien plutôt celle du « mâle », à moins qu’elle ne soit celle du bien du mâle, les bienfaits d’une semence régénératrice. Celle d’un jus pater, sinon d’un « Jupiter », composé d’un radical dont le sens, peu ou prou, est celui de « lumière céleste (jour, ciel, Dieu) » et de pater. Généralement traduit par « père du ciel » mais attesté en latin sous la forme modernisée Diespiter, composé de pater et dies, on peut voir le Dieu des dieux de la mythologie romaine comme la consécration du « Jour du père » sinon qu’entendu ici au sens de dieu, il faut même le prendre littéralement comme « Dieu le père ». De ce jour où l’homme devenu père ou parce que devenu père fut ainsi consacré.
Ainsi, le nachash, cette vipère divine, ne serait que le vit de « Dieu le père », ou plutôt et par cela même, la divinisation du père, la naissance de l’homme, d’un homme comme « père » depuis son vit et par l’entremise de la semence de ces testicules. Mais il y avait sans doute plus à entendre cette hypothétique Création de l’espèce humaine ou de l’humain comme espèce depuis sa distinction de genre à partir de la reconnaissance du rôle masculin dans la procréation. 
1.2 « Dieu est Amour » ou la récupération masculine de la Création
Mais l’analogie féminine devait cependant accompagner la métallurgie jusque dans ses plus tardifs développements. La révélation chrétienne tient en ceci que « Dieu est Amour » et rien d’autre (1Jn4, 8.16)… Cet énoncé constitue le cœur du discours chrétien sur Dieu, celui d’un Dieu interprété comme « amour » et qui constituerait en cela (toute) l’idée chrétienne.
Mais si Dieu est Amour, alors comme à l’occasion d’un fameux « Banquet » platonicien, il convient de se demander à nouveau s’il est dans la nature de l’amour d’être amour de quelque chose, ou de rien? Comme Agathon interrogé par Socrate nous conviendrons également que l’on désire ce que l’on n’a pas, et que l’on ne désire pas ce que l’on a. Si Dieu est Amour, alors Il est l’amour de quelque chose. Mais si Dieu est Amour mais que l’on désire ce que l’on n’a pas, alors Dieu est surtout l’amour de quelque chose dont il est dépourvu. Blasphème des blasphèmes, un Dieu amour ne serait-il justement pas dépourvu d’Amour? Ainsi un prétendu dieu Amour ne pourrait-il pas tout aussi bien être un Dieu a-mour, un Dieu privé de mour… En métallurgie, le mour est « museau de la tuyère », soit  la partie qui s’avance dans le fourneau. 
En métallurgie toujours, la tuyère est une ouverture pratiquée à la partie inférieure et latérale d’un fourneau, et destinée à recevoir le tuyau ou bec des soufflets. Si ce souffle est cet esprit de Dieu, alors comme a-mour, soit privation du museau4, Dieu est un fourneau qui manque un peu d’air… à moins que ce soit Dieu qui ne soit qu’un bas fourneau puisque dépourvu de mour. Enfin, jusqu’à ce que Dieu considère qu’il n’était pas bon pour l’homme d’être seul. Alors Dieu lui créa une compagne à partir d’une de ses côtes, c’est-à-dire qu’il pratiqua une ouverture à la partie inférieure et latérale… du fourneau. Ainsi Ève comme « vivante [animée du souffle (de la vie)] », serait avant tout et pour cette raison même la manifestation de ce souffle. L’avènement d’une nouvelle ère, pour ne pas dire un nouvel air. 
En effet, l’évolution vers un bas fourneau plus efficace consistera à surélever la construction et à munir sa base d’une ouverture latérale pour l’alimentation en air. La maîtrise totale de cette technologie ne sera cependant atteinte qu’au début du XVIIème siècle en Italie grâce à l’apparition d’une nouveauté qui allait devenir la caractéristique la plus originale de la forge, la « trompe ». La trompe est un système de ventilation destiné à entretenir la combustion par soufflage au-dessus d’un foyer bas et ouvert. Mais si la « trompe » est une caractéristique de la forge hydraulique, la trompe qui se dit de certains conduits recourbés et évasés, est aussi en anatomie trompe de Fallope, soit chacun des deux conduits qui relient la matrice aux ovaires.
Si jusque dans ces tardives innovations la métallurgie n’échappe pas à une analogie d’avec la matrice féminine, il y a en cela une raison évidente: cette analogie lui est consubstantielle. Guy Bedos nous avait averti… « Toutes des Fallopes! ». Mais si l’humoriste a toujours raison, nous savons désormais que ce n’est pas parce que les hommes et les femmes se trompent mais bien parce que la théologie est trompeuse.
1.3 La « flétrissure » comme marque négative de la matrice hiérarchique
Ayant perdu l’exclusivité de ce qui avait jusque-là fait sa prédominance et la garantie de sa souveraineté, la « procréation », la femme devait être reléguée à un simple statut de matrone pendant que l’homme pouvait désormais légitimement vaquer à une activité nettement plus transcendantale, l’apprentissage de son divine enfant, la « métallurgie ». Technologie dont l’avènement provoqua une rupture idéologique telle qu’elle marqua l’Humanité au fer rouge. 
Bien que les religions abrahamiques sonnent l’avènement comme la consécration de la phallocratie, l’homme n’aurait jamais pu, ne serait-ce même que pressentir – et par la suite, asseoir – sa domination sur la femme s’il n’était pas parvenu à s’accaparer, s’octroyer ce pouvoir le plus absolu de la mère, celui de la procréation, cette « magie de la grossesse ». 
Et il ne faut pas lire autrement cette réflexion sur l’éversion sinon comme celle du renversement de la prééminence, non seulement dans le terme d’Éversion lui-même, c’est à dire comme renversement idéologique (symbolique) mais aussi dans le sens littéral (anatomique) du prolapsus ce « retournement d’une muqueuse vers l’extérieur » et spécifiquement celui de l’utérus. Celui de l’éversion d’une matrice utérine en testicule pour laquelle l’analogie métallurgique n’est autre, analogiquement, que l’appropriation symbolique par l’homme du pouvoir de procréation féminin, et appliqué à son propre bénéfice. L’éversion de l’utérus comme « matrice organique » en coquille comme « matrice métallique » n’est autre que l’usurpation de l’appareil de reproduction féminin par l’homme à fin de procréation5. 
Ce bouleversement de la prédominance est bien celui de l’Éversion d’une boule, ou plutôt de l’éversion de cette sphère qu’est l’utérus et l’extraversion d’une boule comme « testicule ». Ce prolapsus (cette éversion de la matrice) est analogiquement celui du bouleversement que provoqua ce passage de la prédominance féminine à la domination masculine. Avec la chute de sa matrice, de son piédestal, chut la femme. Ce qui avait fait sa prééminence pendant des milliers d’années était devenue une prérogative masculine. Si la femme enfante d’homme et de femme, l’homme lui a enfanté d’Adam et Ève. Mais lorsque la femme accouche d’enfants, l’homme, lui, donne la vie aux métaux. Si le fruit des entrailles féminines est un enfant, le rejeton masculin est en ferraille.
Comment comprendre sinon qu’avec la Genèse le rapport de subordination s’inverse? Pour être explicite, lorsqu’on passe du plan de la création humaine (la procréation) à celui de la création divine – et alors que la femme a beau être supérieur dans le niveau subalterne que constitue la procréation puisque c’est elle qui, accouchant d’hommes et de femmes, occupe la position englobante ou hiérarchiquement supérieure – c’est l’homme qui va prendre l’ascendant comme on le constate au niveau supérieur de la Création où ce n’est pas Ève qui engendre Adam mais bien Adam qui engendre Ève. Car tel est l’enseignement des religions du salut, l’homme n’a pas été crée par la femme, mais la femme par l’homme. Sinon d’admettre que la Création divine n’est de nature humaine mais métallurgique, il est impossible de comprendre cette ineptie.
De là, nous pouvons démêler un peu plus l’écheveau de notre métaphore matricielle. Plus que comme empreinte d’une « matrice », cette marque négative, taillée en creux au sein de chaque société ou culture apparaît comme une véritable « flétrissure ». En ancien français, flatir signifie « battre les flancs d’une monnaie avant de la passer sous le balancier », de là flétrir, « marquer d’un fer chaud en punition d’un crime ». Mais cette « marque d’infamie » est bien plus sûrement encore une in-fame, la « négation de la femme ». Et Freud ne s’y est pas trompé lorsqu’il déclara que la femme était un homme au pénis rabougris, car la femme dans les religions abrahamiques n’existe pas puisque déjà la première d’entre elle, Ève, n’en était pas une.
Mais lorsqu’il est dit que « L’homme n’a pas été crée par la femme, mais la femme par l’homme » et que dans le même temps, il s’avère que pas plus Adam que Ève ne sont respectivement homme et femme mais bien plutôt « Acier » et « bronze », alors il nous faut entendre que ce n’est pas la procréation qui fait sens, mais bien la Création. Or cette création est celle de la métallurgie et cette métallurgie est la négation de la femme. 

Conclusion (partie I): Le mugissement des héros
L’éversion de la matrice organique en matrice métallique permet à l’homme de prendre analogiquement l’ascendant sur la femme. Pour étayer notre hypothèse de l’origine métallurgique du patriarcat, nous avancerons l’idée mythologique que c’est avec le temps des héros cher à Bachofen que s’accomplie le miracle de remplacer le matriarcat par le patriarcat, si l’on considère cette race des héros comme étant celle de Bronze. C’est d’ailleurs ce que nous allons tenter de démontrer maintenant. 
Engagé au mobile de la souillure d’un lit conjugal6, l’amnistie d’Oreste illustrerait l’issue mythologique de ce combat féroce entre un matriarcat déclinant et le patriarcat ascendant et finalement vainqueur, qui trouva donc son dénouement avec la chute de Troie et la défaite complète et définitive d’Aphrodite, mère de la race d’Énée7. Depuis cette interprétation et aussi dramatique que puisse paraître cette description d’Eschyle, l’Orestie s’impose donc comme un épilogue. Si l’importance mythologique de la Guerre de Troie est à ce point paroxystique et si la « race des Héros » est bien celle qui participa à cette dernière, alors selon notre analyse du mythe des races métalliques, il nous fallait immédiatement convoquer deux d’entre eux à la barre. Si les héros sont étymologiquement « clameurs8 », il s’avérait en effet instructif de s’intéresser au plus prestigieux d’entre eux. 
Dans la mythologie grecque, Stentor (en grec ancien Στέντωρ, Sténtôr) est justement le « crieur » de l’armée des Grecs lors de la guerre de Troie. Son nom vient du verbe στένειν, sténein qui signifie « gémir profondément et bruyamment [mugir] » et passera à la postérité à travers l’expression « avoir une voix de Stentor ». Mais pour bien comprendre cette étrange renommée, il nous faut rapprocher Stentor avec un autre héros de la guerre de Troie qui partage sa qualité vocale, Achille, que l’on décrit comme « voix de bronze ». En associant nos deux héroïques ténors, on peut donc convenir qu’avoir une « voix de stentor » consiste à avoir une « voix de bronze » dont la particularité serait de raisonner tel un mugissement. 
Tout aussi charmante que soit cette définition, elle paraitra effectivement bien inutile à qui ne sait que lorsqu’il en rentre en fusion, l’étain, ce composé du bronze (avec le cuivre), produit comme un « gémissement ». Dès lors, cette race des héros apparaissait pour ce qu’elle était, « une race de bronze », et ce jusqu’à son éventuelle corruption (sa négation). Nous connaissons tous la légende d’Achille9 et de son délicat talon. En revanche savons-nous du Styx10 dans lequel il fut plongé, que l’une des propriétés de ses eaux toxiques est de dissoudre différentes matières, et notamment d’oxyder le métal? Dès lors, il devenait difficile de ne pas voir l’Âge des héros, cet âge qui trouve encore quelques grâces aux yeux des Dieux, ce temps des alliances entre les mortels et les immortels, comme celui des « alliages » et d’un alliage en particulier, le bronze. 
Mais pour peu que l’on adhère à cette réinterprétation, quel est, sinon de mettre un peu de cohérence dans le mythe des races métalliques rapporté par Hésiode, l’intérêt de démontrer que la race de bronze est en fait une « race d’airain » et que c’est la race des héros qui est bien celle de bronze? Ou encore de prétendre que mythologiquement, l’avènement du patriarcat se serait produit pendant l’Âge du bronze? Ces questions sont légitimes mais elles font peu de cas de ce qui a été dit précédemment, à savoir que si les héros trouvent encore quelques grâces aux yeux des Dieu, c’est bien parce que ce temps des alliances entre les mortels et les immortels est celui des « alliages ». Ce qu’il faut entendre, c’est que l’alliage n’est pas perçu autrement que comme une alliance avec les Dieux, en un mot, que cette fusion entre métaux est à concevoir comme une hiérogamie, une « union sacrée », une union sacrée avec les Dieux. 
Autant dire que comme « conjonction », l’amalgame est une prérogative divine. Inutile donc d’insister sur l’évidence que cette alliance avec les Dieux que permettent les alliages, c’est surtout les Hommes, et plus particulièrement l’homme avec un petit « h » qu’elle consacre. Mais le mythe des races métalliques nous le révèle: un temps plus dur attendait la présente « race de fer » qui succéda à celle des héros, où l’humanité trouvait encore quelques biens mêlés à tant de maux.
2. Le début de la domination masculine
Ainsi exposé, il va sans dire que ce manifeste impliquait plusieurs assertions qu’il était nécessaire d’expliciter. Comme il y est question d’anthropologie anarchiste, il paraissait judicieux d’en offrir un état des lieux, une esquisse, pour le moins une axiomatique, sinon quelques prémisses. Cependant, au fur et mesure que s’établissent les primats anarchistes, on s’aperçoit de l’importance croissance que prend le mythe, et ce jusqu’à l’extrême assertion que représente la nécessité de son élaboration. 
2.1 Au commencement… Dieu créa les distinction binaire
Déjà conséquent, la volonté d’établir un mythe anarchiste n’est non seulement pas un acte anodin mais plus encore un acte politique. Explicitement, il s’agit de faire contre-point à un autre mythe, le mythe hiérarchique. Sur cet aspect, il est fondamental d’apporter certains éclairages à partir de la théorie de Louis Dumont. Selon notre auteur, la hiérarchie est avant tout « englobement du contraire ». 
Or, si, rien à ses yeux ne serait plus symbolique que l’englobement matériel de la future Ève dans le corps du premier Adam, ne nous faut-il pas alors en conclure que le mythe de la Genèse est le récit mythologique de la « relation hiérarchique »? Qui plus est, si une idée qui grandit en importance et en statut acquiert la propriété d’englober son contraire11 est lorsque cette « idée » n’est autre que celle d’un « homme » qui non content d’être le prototype mâle de l’espèce humaine en serait aussi le représentant générique au détriment du prototype femelle – puisque les idées « supérieures » contredisent et incluent les « inférieures » –  ne faut-il pas voir dans ce mythe de la genèse hiérarchique avant tout celui de l’androcratie, explicitement du « patriarcat »? 
En conclusion, si la Genèse est bien ce mythe originel d’une hiérarchie d’obédience masculine, ne nous faut-il pas aussi voir dans ce récit l’avènement d’un « principe masculin » et d’en déduire par hypothèse son opposition avec son pendant féminin? Selon notre hypothèse, y voir la confrontation d’un pouvoir hiérarchique masculin à celle d’une puissance anarchique féminine? Tout d’abord ou de prime abord, on peut ne pas être convaincu de cette insertion qui voudrait que la Genèse soit le mythe originel de la hiérarchie. Pour défendre cette hypothèse, convoquons à nouveau à la barre L. Dumont et laissons-le nous développer sa plaidoirie. Comme nous venons de le mentionner, la hiérarchie est essentiellement « englobement du contraire ». Ensuite, la configuration est ainsi, dans le cas normal, « segmentation (de la valeur) ». Enfin, cette hiérarchie inclut  l’« inversion » comme l’une de ses propriétés. 
Certes au niveau du sens commun moderne, la hiérarchie est une échelle de commandement où les instances inférieures sont, en succession régulière, englobées dans les supérieures, et dont la « hiérarchie militaire », construction artificielle de subordination progressive du commandant en chef au soldat, serait l’exemple type. Concrètement, la hiérarchie est une structure dont l’ordonnancement à partir d’un principe commun se répète à l’identique et à échelle variable. Mais si on s’interroge sur ce principe commun d’englobement on se rend compte qu’avant d’ordonner hiérarchiquement, il faut déjà distinguer et qu’est-ce que distinguer sinon établir des oppositions distinctives, segmenter en somme?
Si l’on garde à l’esprit cette définition de la hiérarchie comme un ordonnancement qui induit au préalable l’établissement d’oppositions distinctives ou segmentation et que l’on s’attarde ensuite sur le premier chapitre de la Création du monde… que fait Dieu « Au commencement »? Qu’on en juge un peu dès le premier jour ou Dieu créa les cieux et la terre, sépara la lumière d’avec les ténèbres (le jour de la nuit comme le soir du matin12), puis au second et troisième jour, le ciel de la terre, la terre des eaux, l’humus des végétaux, les végétaux entre-elles (herbe [semailles] et arbres [fruitiers]) et d’avec les animaux, au cinquième jour, les animaux entre eux ({[animaux des mers (poissons) / animaux des airs (oiseaux)] // animaux des terres pédestres [bête sauvage/bête domestiquée (bétail)] / animaux des terres rampants [reptile]}) et enfin au sixième jour, d’avec l’Homme qui devait dominer sur tout le règne animal, végétal et qui sait, minéral. 
Bref, en résumé, en une première semaine, Dieu segmenta le Monde à partir de distinctions binaires en en oubliant presque la plus emblématique d’entre elles, puisque l’homme qu’il avait conçu a son image, à la fois mâle et femelle, était hermaphrodite. 
2.2 Et l’inversion… la semaine suivante
Ainsi la semaine suivant la Création, profitant sans doute de son dimanche chômé pour réfléchir un peu sur sa démiurgie, Dieu se rendit compte qu’il ne pouvait décomposer à outrance une matière même informe et vide sans l’englober dans un ensemble cohérant. Ainsi dans un in extremis sursaut de lucidité, l’éminence céleste créa l’ultime distinction, celle non pas entre mâle et femme mais bien entre « homme » et « femme », et , consubstantiellement, la seconde propriété de l’ordonnancement hiérarchique. Après la « segmentation », vînt l’« englobement du contraire ». 
Ainsi quand l’Eternel Dieu fit tomber un profond sommeil sur l’homme, qui s’endormit, et qu’il prit une de ses côtes pour en former (ou plutôt en forger) une femme… comment ne pas voir cet englobement matériel de la future Ève dans le corps du premier Adam comme le symbole même de l’englobement du contraire? Mais ce n’est pas tout car dans cette curieuse opération, Adam avait en somme changé d’identité, tandis qu’apparaissait un être qui est à la fois membre de l’espèce humaine et diffèrent du représentant majeur de cette espèce. A un premier plan homme et femme étaient identiques, à un second niveau la femme était l’opposé ou le contraire de l’homme. L’opposé ou le contraire, sachant qu’on ne peut être « l’un ou l’autre » dans le sens où l’on serait indistinctement les deux, mais que l’on est soit l’un soit l’autre. 
À la rigueur on peut être l’un et l’autre lorsque l’on est l’un puis l’autre, mais que lorsqu’il en est ainsi, être l’un et l’autre, ce n’est pas être le contraire et l’opposé de quelque chose, c’est être son « Inverse ». Ainsi ou insidieusement, dans sa grande mansuétude – estimant qu’il n’était pas bon que l’homme soit seul et qu’il se mis en tête de lui trouver une aide semblable à lui – Dieu créa la troisième caractéristique de la hiérarchie, soit l’ « inversion ». Pour preuve ultime, cette Inversion ou manifeste conflits et désaccords perpétuels entre le niveau de la conception et celui de l’application même Dieu en fera, et le premier, les frais. Si dans l’idée (conceptuellement) Dieu offrit avec le jardin d’Éden le plus bel écrin au premier couple humain, quelle sera la première chose que feront Adam et Ève quand ils s’installèrent (passèrent à l’application)? 
Rien de moins qu’un parjure qui causa leur exil du paradis originel. Plus prosaïquement, si l’on confère à la hiérarchie une consubstantielle dimension coercitive (et de subordination), alors on ne sera pas surpris d’apprendre que lorsque le sixième jour Dieu fait l’Homme à son image et selon sa ressemblance, ce mimétisme consiste à lui donner le pouvoir de dominer sur les poissons de la mer, les oiseaux du ciel, le bétail et sur tous les reptiles terrestre, bref sur toute la terre et finalement, après la chute de l’Eden, sur sa femme (et ce malgré les désirs qu’elle portera sur lui, tout en lui promettant d’augmenter la souffrances de ses grossesse et d’enfanter dans la douleur).
Tout y était, de la segmentation à l’englobement du contraire en passant par l’inversion et jusqu’à la subordination, la Genèse répondait trait pour trait à la définition hiérarchique. Mot à mot même, et pour cause, puisque plus qu’une simple allégorie, elle en est la parabole, le récit allégorique de la hiérarchie, son mythe.
2.3 Au nom du père… Un si futile syllogisme
La question originelle de la contextualisation qui va suivre consistait à se demander: Comment était-on passé d’un mythologique matriarcat à un mythique patriarcat? Mon hypothèse était que ce passage s’était effectué lorsque l’homme devînt véritablement Homme (en sus, l’humanité à lui tout seul). Mais « Comment le représentant mâle de l’espèce humaine en est-il arrivé à devenir « Homme » ? » était une question autrement plus épineuse. 
Certes je n’imaginais pas que cela se soit opéré autrement qu’à la faveur de la prise de conscience de ce même homme de sa condition de « père » et que j’avais toujours indexée à l’ignorance du rôle des sexes et particulièrement du sexe masculin dans la procréation. Mais comment le démontrer, ou même, à partir de quoi? Pour y parvenir, je suis donc parti depuis la parthénogenèse mythologique, cette croyance en une maternité perçue comme relevant du surnaturel et dont le corps de la femme était dépositaire. En survolant les mythes de l’antiquité grecs, je m’aperçus que la parthénogenèse était la modalité de procréation des divinités primordiales avant l’avènement de Zeus. C’est là que je me suis demandé si cette parthénogenèsie n’était pas plus sûrement à considérer comme l’ignorance de la fonction masculine dans le processus de procréation? 
Qu’avait-il été nécessaire pour aboutir à la « théorie du principe paternel exclusif »? Si au titre de l’histoire, il faut absolument rayer l’hétaïrisme, ce cauchemar ou ce rêve d’indifférenciation et de liberté sexuelle absolue13, par contre, il me semblait devoir le préserver au nom de la « pensée mythique », celle d’une promiscuité originelle. Dans la mesure où on ne pourra jamais parler de Mater incerta, il nous fallait considérer le patrem ciere posse [pouvoir nommer le père de quelqu’un] des romains comme un moment charnière de la vie des peuples, un moment charnière de l’histoire humaine, mais non pas un moment historique, sinon un moment mythologique. 
La tradition mythique non comme une manifestation immédiatement historique est une authentique source de l’histoire en qui l’on peut avoir la plus grande confiance et que son étude serait aussi sûrs et solide en résultats que n’importe qu’elle autre source de connaissance historique… mais bien de puis cette idée que la tradition mythique exprime fidèlement la loi vitale de ces époques dans lesquelles le développement historique du monde [antique] trouve ses fondements, qu’elle exprime la manière dont on pensait aux origines14. Pour résumé ce passage du matriarcat au patriarcat, l’hypothèse de Bachofen était que l’être féminin aurait chercher à convertir cet agresseur potentiel ou systématique qu’est l’homme en un protecteur bienveillant, soit en « mari », en renonçant à la prépondérance que lui consacrait la maternité. 
En effet, si toute l’exclusivisme de la maternité qui ne connaît pas de père et qui considère les enfants comme privés de père – ou, ce qui revient au même, à plusieurs pères – alors se pose le problème idéologique de la formule par laquelle on reconnaitrait la légitimité d’une naissance et sa légitime attribution masculine. Vu ainsi, il est certain que, pour l’homme, le mariage offre ici la meilleure garantie qu’il puisse espérer respectivement à la légitimité du fruit matrimonial. 
Conclusion (partie II): La magie de la grossesse
J’imaginais donc que mythologiquement la rupture avait dû se situer à ce moment précis où l’homme était devenu « père », c’est-à-dire au statut reconnu ou concédé comme tel. En effet, il ne me semblait pas déraisonnable de penser qu’une fois sa paternité établie, cette reconnaissance l’avait définitivement car intégralement fait « homme » et que de la séparation entre les sexes ainsi confortée, la distinction de genre s’en était suivie. 
Mais partant du principe que la culture même la plus archaïque est toujours une culture adulte et que sa structure même élémentaire n’en est pas moins élaborée et complexe, j’avais du mal à me convaincre que les peuples primitifs n’aient pas été en capacité de comprendre ce qui se passait, même à défaut de pouvoir l’expliquer. Comment ces peuples que l’on présume si proche de la nature au point de leur créditer une connaissance immanente de ses lois, n’auraient-ils pas déduit de la simple observation le processus à l’œuvre? Juste par observation du règne animal: comment n’auraient-ils pas pu se rendre compte de l’immuable causalité entre la période du rut et celle de la procréation? Ne serait-ce qu’en observant toute espèce dont les mâles cherchent à tuer leur progéniture pour mieux stimuler les périodes de chaleur des femelles? 
Au pire, à l’échelle humaine, ils leur auraient suffit de soumettre un groupe de femmes au coït pendant qu’un autre groupe était mis à l’écart de toute relation sexuelle pour se rendre compte de l’implication masculine dans la procréation. Sans en concevoir toute la complexité du processus, on imagine mal aussi que ces mêmes peuples n’aient pas saisi l’importance de la semence masculine. Là aussi il leur aurait suffit de faire l’expérience du retrait pour comprendre que c’est bien par le sperme que s’engageait le processus de grossesse et encore qu’il ne soit pas immédiat15. Même si cette hypothèse de l’indistinction des sexes ou de l’ignorance du rôle de l’homme dans la procréation ne convainquait personne d’autre que moi16, je ne l’ai pourtant abandonnée qu’après avoir entendu la réponse que m’apportait mon investigation. 
Mais il m’a fallu du temps pour intégrer l’évidence qui s’écrivait sous mes yeux (et de ma propre main). Encore que nos ancêtres n’en saisissaient pas le processus, l’acte de procréation ne pouvait être un argument infaillible pour expliquer la distinction de genre. L’acte de procréation peut-être… Mais il y avait cependant un point sur lequel le mystère restait entier et le reste encore aujourd’hui et qui confère un avantage décisif à l’être féminin. J’avais mal lu Bachofen, et je m’étais mal lu moi-même. Si pendant si longtemps j’ai pensé que la prééminence féminine mythologique avait pu se fonder sur le mystère qui entourait la procréation et à cette « magie de la grossesse », il n’y avait pas que le mystère qui entourait la procréation. Il y avait aussi cette « magie de la grossesse ». Ce « privilège », c’est la capacité de gestation! 
Sauf en Genèse, jusqu’à aujourd’hui, encore aucun homme n’a pu accoucher ni même être enceint. Mais à croire que l’enjeu est crucial, la Genèse en fait son récit. Si le matriarcat n’est qu’un mythe patriarcal né après coup pour légitimer la domination masculine sous couvert d’« hystérie » féminine, il y a au moins une certitude: La raison d’être du principe masculin réside dans la légitimation de sa supériorité sur le principe féminin. Autant dire que pour l’homme, la partie n’était pas gagnée d’avance. Partant du principe que si l’être féminin avait acquit sa prééminence à la faveur de cette « magie de la grossesse », comment l’être masculin aurait-il pu seulement s’imposer en partant d’une déficience aussi décisive que celle de son incapacité à la procréation et plus encore à la gestation? 
Face à cette carence rédhibitoire, je ne vois qu’une seule réponse: Pour asseoir sa prépondérance, l’homme a dû remédier à cette impossibilité physiologique. Lui aussi a dû faire montre de sa capacité à procréer, sinon que son rejeton à lui ne serait pas organique. C’est donc l’histoire mythologique d’une « coquille » pour ne pas dire celle d’une « coquille17 » de l’histoire que je vous propose de découvrir maintenant. L’histoire d’une inversion car tel est bien le processus à l’œuvre. 

CONCLUSION: D’une Loi d’airain à l’aloi des reins
Si la métallurgie est bien à la genèse de la Création de l’Humanité, sa Genèse, elle imposa non seulement la figure masculine mais, surtout, elle fit disparaître celle de la féminité parthénogenèsique au profit d’une parthénogenèsie masculine. Il y avait cependant dans cette hypothèse un détail des plus troublants. Ce détail était celui du symbole chimique du cuivre « ♀ », soit le même que celui de Vénus et par là le symbole féminin. 
Cette étrange promiscuité de la femme et du cuivre à travers Vénus ne venait en fait que conforter la promiscuité entre la femme et Chypre. Si la femme est intimement liée à Vénus, alors elle est intimement liée à l’île de Chypre, tout comme l’histoire méditerranéenne du cuivre. Mais cette nouvelle contiguïté ne faisait que conforter son commerce avec le cuivre. Ce cuivre rouge on le désignait dans l’antiquité par le terme d’airain, or l’airain a été le plus ancien alliage qui ait servi aux échanges. Si de venor « chasser [prendre en chasse] », de l’indo-européen commun ven « vouloir [désirer ardemment] », notre Vénus à quelque chose à voir avec la « chasse », on peut dès lors se demander si c’est bien la déesse qui était toujours chasseresse ou si elle ne s’était pas plutôt convertie en proie, synonyme de « butin ». 
Or, ce n’était pas l’homonyme de notre déesse, ce vēnus usité uniquement au datif venui, veno « à la vente [à vendre] », variante de venum « vente [trafic] », de l’indo-européen commun wes-no « prix » qui pourrait estomper nos craintes. Si le symbole chimique du cuivre « ♀ » était le même que celui de Vénus et par extension du féminin, que l’airain fut le premier métal qui servit aux échanges, alors on pouvait sérieusement commencer à se demander ce qui prévalait à ces échanges. Plus sûrement, comme le laissaient entendre les coïncidences étymologiques et sémantiques, on pouvait craindre que si la métallurgie du cuivre fut bien à l’origine du patriarcat, elle le fut surtout parce qu’existait désormais une valeur supérieur au féminin mais dont la femme était encore la meilleure monnaie d’échange. 
Comme par enchantement, le mythe de la naissance de venus que nous comte Hésiode dans sa Théogonie relate que la déesse serait née d’une goutte de sang d’Ouranos après que celui-ci fut Émasculé par son fils Cronos. Vénus nait ainsi de la chute dans la mer des organes génitaux de son père. Ce récit concorde d’ailleurs parfaitement avec l’étymologie que donne Porphyre de son pendant grec Aphrodite « Celle qui sort de l’écume de la mer ». L’écume de la mer comme analogie de la « semence du père », belle inversion! Si toute notre réflexion doit se nouer dans cette articulation entre la notion de Valeur et celle d’Échange, alors, et au-delà du simple échange de valeurs ou de la valeur d’échange, il est bien une valeur de l’échange. Si la femme était la monnaie d’échange par essence, l’échange de monnaies est d’essence féminine.
Cette valeur propre à l’échange est celle d’une dynamique, une dynamique que nous considérons volontiers comme celle d’Inversion. Or en termes de valeur, nous sommes tous familiers à la notion d’inversion des Valeurs. Inversons à notre tour la proposition et interrogeons-nous alors sur la valeur de l’Inversion. Comme le souligne L. Dumont, la valeur qui signifiait en latin, « saine vigueur [force] » et désignait au Moyen Âge, la bravoure du guerrier, symbolise aujourd’hui la plupart du temps le pouvoir de mesurer toutes choses en termes de valeur (l’argent). La valeur en usage devînt « valeur d’usage » avant de devenir « valeur d’échange » et finalement échange de valeurs. De l’Écu à nos cartes seule se conserva symboliquement du guerrier la couleur du sang de nos nobles aristocrates, les sangs bleus. 
Si les tribulations de la « valeur » à travers l’histoire de sa notion doivent nous apprendre quelque chose de la fumeuse noblesse de nos valeureux guerriers, au su de notre hypothèse, il ne faudrait guère se leurrer sur la valeur réelle de cette aristocratie. L’Histoire le confirme, leur saga n’est qu’une histoire de faussaires ou plus justement de « faux serfs », ce qui ne constitue en rien une véritable noblesse. Qu’ils en aient acquis ses lettres par la valeur de la robe d’une monture qui contribua surtout à instaurer une aristocratie fort peu cavalière où par la noblesse de leur robe – celle de la connaissance qu’offrait l’éducation d’un clerc – tout n’est question que d’apparat. Or dans l’apparat est aussi la réponse puisque comme on le sait, le mot robe a aussi eu pour sens « butin de guerre ».
Dès lors, il n’y a plus lieu de se demander ce qui a réellement été dérobé sinon détroussé, puisque c’est bien la femme qui semble être l’enjeu de ces tractations. De l’échange de cons (Mariage) à l’échange de coups (Guerre), il n’y a qu’un pas, ou plutôt une passe: une passe d’armes. Si la métallurgie est une « parturition masculine », la guerre comme « épanchement de sang » est-elle une « menstruation masculine »? À moins qu’elle ne soit une « chasse à la femme »?
                        </p>
                    </div>
                </div>
            </div>               
        </section>
        <br>
        <br>
    </main>

    <?php
    //Appel template footer
    require_once("./templates/footer.php");
    ?>