<?php
    //Variable avec le titre de la page
    $title = "Travaux et publications";
    //Appel template header
    require_once('./templates/header.php');
?>
<br>
    <br>
        <section>
            <div class="container">
                    <div class="row">
                        <div class="title col-12">
                            <h2>Travaux et Publications</h2>
                        </div>
                    </div>
            <br>
            <div class="container">
                <div class="row">
                <div class="col-lg-12 mx-auto">
                        <h3>De guerre ne se lasse pas de nous enlacer</h3>
                    </div>
                    <div class="col-lg-12">
                        <img src="" alt="">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text">
                          <p>Cette réflexion sur l’« aide au développement » comme Continuation du commerce politique par d’autres moyens est le fruit de la maturation de mon travail de DEA. Mon hypothèse est que le « principe d’inversion », caractéristique de la hiérarchie selon L. Dumont, permet parfaitement d’expliquer le renversement que l’on rencontre entre la conception, somme toute louable de l’éthique tiers-mondiste et l’application plus que douteuse, parfois condamnable que l’on peut constater sur le terrain. </p>
                          <h4>1. L’humanitaire comme continuité de l’impérialisme par d’autres moyens</h4>
                          <p>C’est donc une application scrupuleuse de la conception dumontienne de la hiérarchie comme « englobement du contraire » au champs développementariste que je propose ici. Si essentiellement comparative, condamnée à la vacuité, faire la propagande du relativisme et fleurer bon l’euphémisme et l’embarras… l’« aide au développement » semblait néanmoins offrir aux yeux de L. Dumont une contrepartie modeste mais non dénuée de sens pour l’anthropologie. Une contrepartie dont nous saurions retirer un avantage théorique immédiat puisqu’il s’agira ici d’appliquer la théorie de Louis Dumont sur l’objet d’étude que constitua notre expérience humanitaire au Mali.</p>
                          <h4>1.1 L’équistatuté imaginaire</h4>
                          <p>Égalité de principe, iniquité de fait! Ce triste constat, on le doit au présupposé erroné qui est à l’origine de l’aide au développement. Fidèle à notre idéologie moderne, on a tendance à considérer les partenaires comme égaux, or ils ne le sont absolument pas. S’ils ne le sont pas dans les faits, ils le sont encore moins par principe. </p>
                          <p>S’ils ne peuvent pas l’être c’est en relation à ce qu’on appelle la Modernité et ce, pour la bonne et simple raison que le Nord l’incarne et que le Sud personnifie dans l’imaginaire collectif son contraire, à savoir la Tradition. Leur relation est donc asymétrique au regard de l’idéologie globale. Dans ce contexte peut-on considérer que les deux pôles aient un statut équivalent ? « Certainement pas! », nous répondrait Louis Dumont. Dans ses Éssais sur l’individualisme, l’auteur estime que cette opposition entre un Tout et un élément de ce Tout (ou Partie) ne peut-être que hiérarchique. La relation entre Parties et Tout est hiérarchique or une relation différente signifie une place différente dans la hiérarchie. Les deux termes ou pôles n’ont pas un statut égal, l’un est supérieur, l’autre inférieur. </p>
                          <p>Comment se fait-il alors que les deux opposés que nous prenons comme égaux ne le soient pas ou pourquoi la prééminence de l’un sur l’autre? Ce qui manque nous dirait Dumont, c’est de reconnaître que le couple Nord/Sud n’est pas définissable en lui-même mais seulement en relation à un Tout, à un Tout nommé Modernité. Or si la relation hiérarchique mise en évidence entre Nord et Sud est bien celle entre un Tout (ou un ensemble) et un élément de ce Tout (ou sous-ensemble) alors cette relation ne peut être que hiérarchique. Ce truisme serait seulement obscurci quand le pôle supérieur d’une opposition hiérarchique coïncide avec le Tout et que le pôle inférieur est déterminé seulement en relation avec lui comme c’est le cas entre Tradition et Modernité et à l’image d’Adam & Eve1. </p>
                          <p>Dans cette théorie, chaque élément fait partie de l’ensemble, lui est en ce sens consubstantiel ou identique, et en même temps s’en distingue ou s’oppose à lui. La distinction hiérarchique réunit le donné en soudant deux dimensions de distinction: entre niveaux et à l’intérieur d’un niveau, ce que notre auteur nomme « englobement du contraire » et dont l’exemple symbolique n’est autre que l’englobement de la future Ève dans le corps du premier Adam. La saisie hiérarchique d’une opposition comme celle entre Nord et Sud nous renvoie à la distinction de niveaux dans l’« idéologie globale ». En situant les deux pôles dans l’asymétrie de leur relation apparaît une « hiérarchie de niveau ». </p>
                          <p>En faisant ainsi l’économie du recours à l’opposition binaire, nous éviterons de voir superficiellement des incompatibilités ou une équistatuté imaginaire, là où un examen plus attentif révèle des différences qui sont fonctions de cadres de référence différents.  </p>
                          <h4>1.2 L’englobement du contraire</h4>
                          <p>Peut-on pour autant établir une supériorité de l’une des parties sur l’autre, ce que laisserait entendre une conception couramment admise de la hiérarchie? </p>
                          <p>Qu’en réalité les deux pôles aient des valeurs inégales, que l’une soit sentie comme supérieure à l’autre nous apparaît comme un trait arbitraire, surajouté. Une fois attribuée la prééminence à l’une des parties, l’autre globalement inférieure, se révèle pourtant supérieure à des niveaux secondaires. Le fait est que, une fois certaines fonctions attribuées à la partie inférieure, la partie prééminente tout en restant dans l’ensemble supérieure, sera seconde quant à l’exercice de ces fonctions. La supériorité des uns et son corollaire, l’infériorité des autres n’auraient donc aucune influence sur les relations qu’ils entretiennent entre-deux. Selon notre auteur, c’est la référence au Tout comme à un Tout auquel appartiennent les Parties qui prime, or cette référence est seulement constitutive de chacune d’elle et de leur distinction. </p>
                          <p>Quant au tout, il n’est pas préférable à ses parties, il leur est simplement supérieur. L’exemple de la main droite et de la main gauche de Hertz est à ce titre édifiant2. Ainsi, c’est la référence au corps comme à un Tout auquel appartient main droite et main gauche qui est constitutive de la droite, de la gauche et de leur distinction. Plus que sur leur distinction en termes de valeurs comparatives, c’est sur leur relation asymétrique au regard de l’« idéologie globale » qu’il nous faut nous attacher. C’est ainsi que les pôles et leurs attributs sont tout à la fois différents et respectivement supérieurs et inférieurs. En la matière, Nord et Sud ne sont pas dans le même rapport au Tout « Modernité ». </p>
                          <p>Dans cette logique, il faut les différencier en valeur en même temps qu’en nature. En référence à l’idéologie globale, « Modernité », le Nord apparaît plus important, plus essentiel, plus représentatif, etc. que le Sud. La prééminence n’est pas ici contingente, mais nécessaire, car elle résulte de la différenciation des deux termes par rapport au Tout. Loin d’être scandaleuse, la distinction contingente des statuts ne serait plus nécessaire mais salvatrice. Par ce tour de passe-passe Dumont espère faire l’économie du risque d’oppression inhérente à toute subordination hiérarchique, notamment parce qu’il a en tête l’étiquette hautement élaborée de la chine traditionnelle. </p>
                          <p>Dans ce modèle d’équité, il devient possible de différencier chaque situation de toute les autres et de réduire ainsi à zéro le résidu d’insignifiance de l’idéologie en ayant intensément recours au renversement dans un ensemble complexe d’oppositions et d’homologies.</p>
                          <h4>1.3 La nature de l’idéologie</h4>
                          <p>Un idéal de hiérarchie en somme, mais un idéal pour une hiérarchie idéale ou une hiérarchie idéalisée? De cette conception de la hiérarchie, retenons essentiellement la définition d’un Tout comme garantissant l’interdépendance et la cohérence interne. Du point de vue de Dumont, cette conception est traditionnelle et structurale et elle articule une relation spécifique entre la connaissance et l’action. </p>
                          <p>Ici, l’accord est garanti au niveau de la société: les idées sont en conformité avec la nature et l’ordre du monde, et le sujet n’a rien de mieux à faire que de s’insérer consciencieusement dans cet ordre. Voici exposée idéalement la théorie de l’opposition hiérarchique de Louis Dumont. Il ne faut pourtant pas perdre de vue, qu’en sa qualité de spécialiste du système de castes indien, Louis Dumont, lorsqu’il pense hiérarchie, n’imagine pas autre chose que des distinctions de valeurs, nombreuses, fluides et flexibles, qui courent indépendamment les unes des autres en un lacis de faible intensité, diversement accentuées selon les situations, tantôt venant au premier plan, tantôt s’estompant… Un idéal de hiérarchie en somme qui combine plénitude, continuité et gradation où chacun aurait sa place car serait à sa place, et qui plus est une place juste, ajustée. </p>
                          <p>Une juste place pour laquelle le sujet n’aurait rien de mieux à faire que de s’insérer consciencieusement dans l’ordre... établi. Mais cet ordre du monde où les idées sont en conformités avec la nature a-t-il bien été établi par la nature ou n’est-il pas seulement fondé en nature pour mieux légitimer les inégalités criantes qu’il génère au sein de l’humanité? Mais il est vrai que la question importe sans doute peu à quelqu’un qui à fait sienne la doctrine darwiniste de Saint-Thomas qui veut que « L’ordre consiste principalement en inégalités ». Et s’il devait y avoir une ratée dans cette belle mécanique, du genre dérive totalitaire, la faute en reviendrait de toute évidence selon Louis Dumont à une certaine pensée moderne qui a tendance à confondre hiérarchie et pouvoir… Tout va donc pour le mieux dans le meilleur des mondes… Thomasien. </p>
                          <p>D’ailleurs, il est indéniable qu’une analyse des rapports Nord-Sud calquée sur le modèle de l’opposition hiérarchique explique parfaitement bien l’asymétrie des statuts et l’iniquité de leur relation. L’analyse est même à ce point parfaite, qu’elle semble indiscutable au point où nous ne la discuterions pas. Elle recèle cependant une faille et cette faille se situe dans la perfection même de l’analyse. Si une approche par l’opposition hiérarchique décrit si bien le mécanisme de l’aide au développement c’est tout simplement que celle-ci s’inscrit dans un principe hiérarchique. Après avoir, en toute impunité, dédouané la hiérarchie de toute forme de coercition et de domination, L. Dumont affirme que contrairement à l’égalitarisme, la hiérarchie procure du sens. </p>
                          <p>Mais cela signifiait-il pour autant comme le préconisait Louis Dumont qu’il y ait un besoin de réintroduire quelques degrés de holisme dans nos sociétés individualistes, et que cela ne pouvait être fait que hiérarchiquement à des niveaux subordonnés clairement articulés, de manière à empêcher tout conflit majeur avec la valeur prédominante? A ce second niveau – où l’on considère un type de société ou de culture donnée – la primauté se retourne nécessairement et le holisme s’impose. En somme, c’était en hiérarchisant à la fois les niveaux de considération et, à l’intérieur de ceux-ci et de façon contraignantes, ces deux principes, qu’il pensait venir à bout – idéalement – de l’incompatibilité qu’il avait rencontrée. </p>
                          <p>Suffisait-il seulement de rétablir notre conception de l’aide au développement dans un système hiérarchique pour que celle-ci prenne tout son sens… et devienne véritablement effective? Comme l’écrit Dumont, cette hiérarchie de niveau résulte de la nature même de l’idéologie. Ainsi, c’est parce que l’idéologie dominante est toute tournée vers la hiérarchisation que les niveaux sont hiérarchiques...</p>
                          <h4>Conclusion (partie I): Sacré truisme, maudit chiasme</h4>
                          <p>Louis Dumont estimait qu’on s’apercevrait à la longue que la solution consisterait à donner à l’un et à l’autre des deux principes opposés son champ légitime de suprématie. Du point de vue moderne, l’individualisme régnerait mais consentirait à se subordonner dans des domaines subordonnés… Il ne s’aperçut pourtant pas que le sous-Tout qu’il aurait fallu créer existait déjà. Ce dont témoignait parfaitement le champ du développement puisqu’il le justifiait, à savoir le « Tiers-monde ». </p>
                          <p>Lui qui préconisait de distinguer des niveaux, peut-être en grand nombre, et sans doute à l’image de ce que pouvait être l’étiquette chinoise, ne perçut pas davantage que cette recommandation était déjà aussi opératoire à travers des sous-catégories comme « développé », « en voie de développement », « sous développement », « mal développement » « en retard de développement », etc. Or, si tout ce qu’il y aurait eu à faire était déjà affairant, cela ne pouvait signifier qu’une seule chose: le procédé était déjà à l’œuvre. En effet si l’aide au développement s’inscrit si bien dans une approche par la hiérarchie, c’est tout simplement que celle-ci est déjà l’émanation d’un processus hiérarchique. Dumont nous conduit à un truisme: c’est bien parce que l’idéologie dominante est toute tournée vers la hiérarchisation que les niveaux sont hiérarchiques.  </p>
                          <p>L’analyse des relations nord/sud calquée sur le modèle de la relation hiérarchique nous permet certes d’identifier la genèse délétère de ce don de soi altéré en don de seoir qu’est l’aide au développement mais surtout d’apprendre que le monde est hiérarchisé. Mais, si cette hiérarchie de niveau résulte de la nature même de l’idéologie, en clair, si tout est hiérarchie et que la hiérarchie est parfaite, comment l’imperfection moderne? S’il devait y avoir une ratée dans cette belle mécanique, cette loupée était-elle imputable à un manque de hiérarchie ou à un usage outrancier de cette dernière? Ainsi lorsque pour répondre aux incompatibilités rencontrées, la solution consiste à réintroduire davantage de hiérarchie, alors-là, il n’est même plus question de truisme, mais de chiasme: Mieux vaut une fausse vérité hiérarchique que l’erreur d’un égalitariste vrai. </p>
                          <p>Je ne pouvais dès lors suivre Dumont sur des chemins si captieux. Si telle était bien l’esprit, sinon l’âme, de son entreprise, alors je devais m’en dissocier. Mais si cette dissociation était aisée par principe, elle l’était beaucoup moins dans les faits, puisqu’en réalité nos relations entre êtres humains et conséquemment à notre rapport au monde étaient bel et bien régis par le principe hiérarchique.</p>
                          <h4>2. Le commerce comme moyen de la continuité de la guerre idéologique</h4>
                          <p>Que notre rapport au monde soit régi par le principe hiérarchique était une chose, mais que cet état de fait s’éternise en était une autre. Si théorie à l’appui, je pouvais affirmer que la hiérarchie était la matrice de l’aberration que représentait à mes yeux ce monde, il me fallait encore la combattre et la vaincre. </p>
                          <h4>2.1 Une complémentarité de niveaux: « À l’intérieur d’un niveau et entre niveaux »  </h4>
                          <p>Pour contrer cette misère de l’esprit qui fait oublier à l’esprit sa propre misère, il ne faisait aucun doute pour moi qu’il n’y avait qu’une seule manière de procéder: Si le cœur du problème était la hiérarchie alors, à première vue, la stratégie la plus judicieuse consistait à faire plier la hiérarchie sous son propre joug. </p>
                          <p>Prendre la hiérarchie à sa propre infamie ne signifiait rien d’autre que « hiérarchiser la hiérarchie ». En effet, si la hiérarchie consiste à hiérarchiser et que l’on poussait la logique jusqu’au bout, jusqu’à l’absurde certainement, alors viendrait le moment où la hiérarchie serait elle-même hiérarchisée et automatiquement, elle s’annulerait. Toute théorique que pouvait paraître cette manœuvre, elle n’en suivait pas moins scrupuleusement les indications de Louis Dumont. Et pour commencer, si la distinction hiérarchique réunit le donné en soudant deux dimensions de distinction, à l’intérieur de chaque niveau et entre niveaux, alors nous pouvions caresser l’espoir de venir à bout de la hiérarchie soit en la hiérarchisant à l’intérieur d’un niveau soit en opposant les niveaux. </p>
                          <p>Et à quelque degré supérieur que ce soit, nous contrecarrions la logique hiérarchique avec l’argument qui veut que « la fin ne peut pas être son propre moyen ». Hiérarchiser la hiérarchie à l’intérieur d’un même niveau consistait à la confronter à une valeur concurrente, la hiérarchiser entre niveaux revenait à hiérarchiser la hiérarchie avec elle-même. Et, s’il devait s’avérer que la hiérarchie représenterait univoquement le pôle supérieur des opposition asymétriques à venir, il nous suffirait certainement de pousser la vertu un peu plus loin, de monter encore d’un cran dans l’échelle des Touts, jusqu’à cet ultime échelon qu’incarne l’Entité supérieure là où même le Grand Tout, l’univers ou Tout-des-Touts, dérive sa propre valeur et de là, provoquer nous-mêmes le renversement.</p>
                          <p>Dans l’immédiat, restait donc à identifier cette éminente valeur complémentaire qui représenterait éventuellement le pôle supérieur de cette décisive opposition hiérarchique. La chose était des plus évidentes car pour déterminer cette valeur, il suffisait de s’appuyer sur les dires de Dumont concernant les formes pratiques d’intégrations. Selon notre auteur, si les valeurs (sociales) sont essentielles pour l’intégration et la permanence du corps sociétal et aussi de la personnalité ou de l’identité de l’individu, il y aurait deux façons de reconnaître en quelque façon l’Autre: la « hiérarchie » ou le « conflit ». Si Louis Dumont confessait sa préférence irénique pour la hiérarchie, nous autres, en accord avec Max Weber et une certaine tendance moderne, confessions notre préférence idéologique pour le conflit. </p>
                          <p>Ceci dit, que le conflit soit inévitable et peut-être nécessaire était effectivement une chose, le poser comme idéal ou comme « valeur opératoire », en était une autre. À notre décharge, cette préférence était également théorique puisque si la fin ne peut pas être son propre moyen alors la même entité ne pouvait pas être à la fois complète en soi et être dépendante à un degré quelconque de quelque chose d’autre. Or, malheureusement pour L. Dumont, il n’en allait pas autrement de son concept de hiérarchie. En effet, ou bien les prétendues « valeurs opératoires » n’étaient pas des valeurs du tout, ou bien elles étaient des valeurs du second ordre, à distinguer clairement des valeurs du premier ordre, les valeurs proprement dites. En effet, si la hiérarchie était universelle, elle ne pouvait prétendre à la fois être une valeur conçue (cardinale) et la valeur opératoire. </p>
                          <p>S’il y avait un besoin de réintroduire quelques degrés de holisme ou de hiérarchie dans nos sociétés individualistes, ce ne pouvait donc être fait hiérarchiquement, à moins de considérer que la hiérarchie n’était pas une valeur universelle mais seulement une valeur du second ordre. Dès lors, soit la hiérarchie n’était pas universelle, soit il en était fait de sa capacité opératoire. De guerre lasse, déjà délicate d’un point de vue éthique, cette prise de position ne l’était pas moins du point de vue théorique. Puisque si la meilleure illustration du rapport entre hiérarchie et conflit était ce concept de commerce politique clausewitzien, la difficulté n’allait pas tarder à surgir à travers son retournement par Foucault. </p>
                          <p>Depuis la relecture foucaldienne ce n’était plus « la guerre » qui était la continuation de la politique par d’autres moyens mais bien la « politique » qui était la continuité de la guerre par d’autres moyens.</p>
                          <h4>2.2 Une alternance de la prééminence:  « Le changement de niveau »</h4>
                          <p>Par d’autres moyens, pour ne pas dire que cet autre moyen n’était autre que la fin précédente, en clair que la fin était devenue son propre moyen et le moyen sa propre fin. L’impensable était devenu réalité. Ce renversement ou ainsi cette « complémentarité des niveaux d’expérience » que nous constations à travers les temporalités de l’époque moderne et que révélaient les conceptions antithétiques de Foucault et Clausewitz renvoyait directement à une « alternance de la prééminence ». </p>
                          <p>Une complémentarité de niveau qui semblait surtout avoir établi la prééminence d’un ordre désormais mondial. Encore que l’opposition inversée se rencontrant dans le même Tout où l’opposition directe était présente indiquait à l’évidence un changement de niveau, jamais la hiérarchie ne serait renversée car toujours elle inversait le lien de causalité. Un changement de niveau qui pour l’heure n’arrangeait en rien nos affaire puisque l’alternance de la prééminence entre « hiérarchie » et « conflit » constatée au gré des temporalités modernes ne nous permettrait non seulement pas d’établir une quelconque sujétion de la hiérarchie au conflit mais démontrait bien plutôt leur inaliénable complémentarité. </p>
                          <p>Plus grave encore, s’il pouvait être admis qu’à l’époque contemporaine, le conflit avait certainement pris l’ascendant sur la hiérarchie, ce changement de niveau semblait avant tout conforter un ordre à l’échelle mondiale. Que ce changement conforte un ordre mondial n’était évidemment pas pour nous rassurer car rencontrer un ordre n’était pas véritablement l’objectif que nous poursuivions en tentant de hiérarchiser la hiérarchie par le conflit. Pire encore, comment concevoir l’extension planétaire de cet éminent englobement autrement sinon qu’à travers sa terminologie consacrée, la « globalisation »? Le renversement était en marche, le « commerce politique local » était devenu une « politique commerciale globale », une guerre économique comme continuum d’un commerce idéologique. </p>
                          <p>Ce renversement de la proposition – ou lorsque l’opposition inversée se rencontre dans le même Tout où l’opposition directe était présente – ne pouvait signifier qu’une seule chose, nous avions bel et bien changé de niveau. Mais cet ordre globalisant pouvait-il foncièrement être différent de celui où les idées sont en conformité avec la nature et l’ordre du monde et dans lequel le sujet n’a rien de mieux à faire que de s‘insérer consciemment ou « ordre holistique »? Radicalement différent de cet ordre dont la plus parfaite expression n’est autre que la hiérarchie? De toute évidence, non! </p>
                          <p>Nous n’en sortions pas et il paraissait chaque fois plus évident que nous ne nous en sortirions pas de la sorte. La logique semblait infaillible. Il n’était désormais plus à douter que le schéma se reproduisait à l’infini, qu’indéfiniment la hiérarchie nous ferait volte-face, que jamais elle ne se laisserait mater. Il ne nous restait donc plus qu’une seule alternative, il nous fallait remonter là où la hiérarchie prenait sa source. Pour cela, il nous fallait rejoindre l’infini, aller jusqu’au bout de l’univers et sans doute même au-delà, dans l’Au-delà certainement même. Une fois encore, nous dûmes accorder quelques crédits aux allégations de Louis Dumont, tout particulièrement lorsqu’il nous averti que le Tout particulier est un Tout partiel (holon), lui-même partie d’un Tout partiel supérieur. </p>
                          <p>Il nous fallait donc prendre pour acquis que ce qui était vrai pour des holons, devait aussi l’être pour le Grand Tout, l’univers ou Tout-des-Touts. S’il était donc bien vrai que ce Tout supérieur ait besoin à son tour d’une entité supérieure d’où il dérive sa propre valeur, et s’il devait s’avérer exact que la hiérarchie était universelle, alors il ne nous restait plus qu’à nous propulser dans le cosmos afin de découvrir à partir de quelle entité supérieure la « hiérarchie » dérivait sa propre valeur, sa valeur universelle. Et à ce stade nous avions encore une carte à jouer car écrite dans la structure, est l’inversion. La seconde fonction aussitôt définie, elle implique l’inversion pour les situations qui lui appartiennent. </p>
                          <p>En d’autres termes, la hiérarchie est bidimentionnelle. Elle ne porte pas seulement sur les entités considérées, mais aussi sur les situations correspondantes et cette bidimentionnalité implique l’inversion. Si l’inversion était écrite dans la structure universelle, alors nous nous lancerions à l’assaut de l’Univers.</p>
                          <h4>2.3 La hiérarchie comme matrice universelle: « Le Surtout ou la source de la valeur » </h4>
                          <p>Nous partîmes donc avec la ferme intention de rallier cette source d’où dérive la valeur. Et s’il devait s’avérer que son cours était univoque alors, en ultime instance, en définissant nous-mêmes la seconde opposition, nous provoquerions l’inversion et en changeant ainsi de niveau, sans rémission, aucune, renverserions la hiérarchie.</p>
                          <p>En attendant, Louis Dumont nous l’avait appris, chaque configuration particulière d’idées et de valeurs est contenue avec toutes les autres dans une « figure universelle » dont elle est une expression particulière. Pourtant, cette configuration universelle était si complexe qu’elle ne pouvait être décrite, mais seulement vaguement imaginée comme une sorte d’intégrale de toutes les configurations. Mais s’il était impossible de saisir la « matrice universelle » dans laquelle la cohérence de chaque système de valeurs était enracinée, elle était perceptible d’une autre façon. La hiérarchie de niveaux résultait de la nature même de l’idéologie, poser une valeur, c’était en même temps poser une non-valeur. C’était constituer un donné où il resterait de l’insignifiant. </p>
                          <p>Or, cet Insignifiant ne pouvait être limité comme l’idéologie l’exigeait pour se justifier à ses propres yeux, que parce que la « valeur » s’étendait graduellement sur lui en se dégradant progressivement. Au-delà d’un certain degré, tout se passait comme si la « valeur » occultait ce qu’à l’ordinaire, elle révélait. L’idée fondamentale, l’« Idée-mère » demeurait inexprimée mais son emplacement était indiqué par la prolifération d’« idées-valeurs » dans la zone même où elle se cachait. Ainsi, chaque société ou culture portait la trace de l’inscription de cette idéologie à l’intérieur de la condition humaine. C’était peut-être une marque négative, taillée en creux, mais c’était avant tout la marque de la Matrice universelle dans laquelle la cohérence de chaque système de valeurs était enracinée. </p>
                          <p>Ainsi et seulement ainsi devenait-il concevable d’identifier la Matrice universelle et qui sait, cette configuration des configurations nous permettrait-elle d’identifier cette énigmatique « figure universelle » et d’établir ainsi l’intégralité du Sur-tout. La difficulté était que si déjà dans une idéologie favorable à la hiérarchie, l’Idée-mère de la Matrice universelle demeurait souvent inexprimée, il était à craindre qu’une idéologie moderne, hostile à la hiérarchie se devait de comporter tout un réseau de dispositifs pour neutraliser où remplacer la relation en cause. </p>
                          <p>Si des relations hiérarchiques étaient assurément présentes dans notre idéologie moderne, elles ne se donnaient évidemment pas comme telles. Il en était ainsi chaque fois qu’une valeur était concrètement affirmée, elle subordonnait son contraire mais on se gardait bien de le dire. Pour appréhender le phénomène, nous décidions de sonder les différentes stratégies employées par cette idéologie hostile au holisme. Tout d’abord nous apprîmes que l’on pouvait éviter le point de vue où la relation apparaissait en produisant des Ensembles et non plus des Touts. Ce faisant nous découvrîmes bientôt que le dispositif le plus récurent consistait à introduire une distinction absolue entre faits et valeurs. En Modernité, la transition des faits aux valeurs n’était plus possible, jugements de réalités et jugements de valeur étaient désormais de nature différente.</p>
                          <p>Mais à occulter ainsi la hiérarchie de niveaux, cette séparation des éléments ne favorisait pas seulement la substitution d’une vue plate à une vue en profondeur… Elle provoquait la suppression de la subordination ou pour l’appeler de son vrai nom, de la « transcendance ». Diantre! Avec un pareil nom, il nous devenait relativement évident de découvrir qui pouvait se cacher derrière cette énigmatique figure universelle. La seule que nous connaissions ou qu’il ne nous ait jamais été donné de connaître, sans l’avoir jamais connue d’ailleurs, en un mot « Dieu »! Tout ça, pour ça! La mise à l’écart de l’Idée-valeur prééminente, soit la Subordination, n’avait fait qu’occulter la Transcendance comme « idée-mère ». Affublé de tels oripeaux, pas étonnant alors que le Grand Tout, l’univers ou Tout-des-Tout ait besoin à son tour d’une « entité supérieure » d’où il dérive sa propre valeur. </p>
                          <p>À l’image de chaque configuration particulière d’idées et de valeurs, l’univers était contenu dans une figure universelle qui n’était autre que la figure tutélaire de Dieu. Le Sur-tout ou Dieu comme source de toute valeur, le camouflet était sévère.</p>
                          <h4>Conclusion (partie II): Une théologie négative comme révélation</h4>
                          <p>Notre tentative pour inféoder la hiérarchie au conflit avait lamentablement échoué face à une inflexible complémentarité qui était justement celle qui, depuis des millénaires, nous faisait plier sous le joug de la servitude. Pourtant et bien que cette tentative se soit finalement fracassée sur l’imposture d’un Dieu omnivalent, nous ne nous résignerions pas pour autant. </p>
                          <p>Nous porterions le conflit à un autre niveau ou plutôt nous engagerions un conflit d’un autre ordre. Si le conflit n’était finalement qu’un échange de maux, alors c’était par les mots que nous vaincrions le mal hiérarchique. Si cette violence devait être prise à la lettre, alors c’est par la polémique que nous continuerions le combat. Par la polémique, car si la polémique appartient à la dispute, depuis le grec ancien, polemikós est surtout cet art « relatif à la guerre ». Vînt alors le temps de poser le conflit non plus comme « valeur opératoire » mais bien comme idéal, un idéal éristique. Notre lutte acharnée nous avait conduit aux confins de l’univers, c’était donc dans ses contreforts que nous mènerions le combat final. Avant cela il nous fallait clairement identifier l’adversaire.</p>
                          <p>Et pour commencer, si la Transcendance comme marque de la « matrice hiérarchique » est bien la trace de l’inscription négative et taillée en creux d’une idéologie, alors nous devions considérer le Holisme comme une non-idéologie. Mais cette non-idéologie n’en était pas une, ou plutôt si elle l’était, elle était bien davantage comme « idéologie négative » car en holisme, lorsqu’on parle de « non-valeur », il faut seulement y voir une valeur occultée. L’artifice holistique de la « non-valeur » comme valeur occulte est celle de la « Révélation » et cette non-idéologie comme idéologie négative ne saurait être autre que l’extension parfaite de la « Théologie négative ». Cette fois, le champ était en ordre de bataille. </p>
                          <p>La « subordination » était l’Idée valeur prééminente d’une Idée-mère nommée « transcendance » et d’un Ordre « holistique » dont la « hiérarchie » serait la Matrice universelle et « Dieu » la Figure tutélaire. La source d’une non-valeur depuis toujours « révélation », et dont la concomitance non idéologique n’était que la résurgence d’une « théologie négative ». Un lieu commun que conforte le pseudo Denys l’Aréopagite lorsqu’il écrit que le but de la hiérarchie est une assimilation et union à Dieu. Bienvenu dans le monde merveilleux du holisme, cette cité de Dieu où la hiérarchie serait la plus parfaite expression d’un ordre qui régente une condition humaine dont la manifestation ne serait que négative.</p>
                          <p>Une inhumanité marquée de l’intérieur du sceau de l’infamie, la flétrissure d’une inscription obscure et contraignante, celle d’une idéologie délétère que porteraient chaque culture et société. L’idéologie d’un ordre inégalitaire qu’il serait plus juste de considérer comme ordre thomasien, si l’on veut bien rendre la politesse de la formule à qui elle appartient. Et l’on s’étonnerait ensuite que l’idéologie de cet ordre soit négative quand son théoricien n’est autre que le penseur de la « théologie négative »? Guère surprenant donc que la transcendance ainsi posée et en relation à laquelle le monde se situait n’établisse de l’expérience humaine qu’une explication négative. Qu’à cela ne tienne, à la négation nous répondrions par la négation. Mais pour trouver ce quelque chose au dessus de Dieu afin qu’il puisse se subordonner et ainsi enfin s’intégrer en lui-même, nous n’avions guère le choix que de nous engager dans l’Au-delà. </p>
                          <p>Et c’est bien depuis l’outre-monde que vînt la lueur d’espoir. Une lueur à la source même de la Lumière divine, car si Dieu est la Lumière, mais que la Lumière fut seconde quant au Verbe, alors le Verbe précède Dieu puisqu’il précède sa lumineuse étymologique. Dieu avait-il ainsi bénéficié d’un traitement de faveur? Et si dieu avait bénéficié d’une inversion? À moins que ce ne soit l’inverse? Si l’inversion était divine, alors notre véritable Dieu n’était pas dieu, mais l’inversion. Au-delà de Dieu, il y a l’inversion, la divinité insignifiée mais primordiale c’est l’Inversion. D’ailleurs si hiérarchiser signifie « classifier », cet éclat du verbe « clamer » qui fut d’abord celui de la « voix » (donc du Verbe), puis de la « clarté » (de la Lumière) avant de se référer au « brillant » (l’Esprit) n’était-il pas parfaitement à l’image de Dieu? Sémantiquement, dieu n’était que la transfiguration de la hiérarchie, or si la hiérarchie était inversion alors nous renverserions Dieu. </p>
                          <p>L’outre-monde, l’au-delà de Dieu, ce lieu éloigné d’où on regarde derrière soi avec détachement l’expérience humaine, ce royaume de l’insignifiant était celui de l’Inversion. Tant est si bien d’ailleurs qu’il était tout aussi vrai que, tel son négatif, l’explication du monde que fournissait l’ultra-mondanité était négative3.</p>

                          <h4>CONCLUSION: L’intégralité par l’intégralité</h4>
                          <p>À ce stade de la réflexion, il nous fallait bien reconnaître que si l’analyse théorique de Louis Dumont embrassait si pleinement l’expérience empirique, il ne pouvait y avoir qu’une seule raison logique valable: l’expérience empirique n’était que l’expression de l’analyse théorique. </p>
                          <p>Or, si cette expérience empirique n’était que l’expression d’une analyse sociologique effectuée à partir d’une saisie théorique de la hiérarchie, alors il nous fallait accepter l’évidence que l’expérience empirique était assujettie au dictat de la relation hiérarchique. La seule indélicatesse était que cette expérience était malheureusement la nôtre. D’évidence, si l’on admettait que cette réalité n’est que le jouet d’un processus hiérarchique alors c’était bien entendu la hiérarchie qu’il convenait de renverser. Mais s’il était établi que la hiérarchie n’était que l’oripeau, la guenille de l’inversion, alors c’était surtout le processus d’inversion qu’il nous fallait enrayer. Contrairement aux apparences, ce processus n’était pas vil en lui-même mais vil il pouvait devenir et même devenait quand imparfaitement il s’exprimait. </p>
                          <p>Le corriger consistait donc à en rétablir l’intégrité par l’intégralité. Si la relation hiérarchique ne saurait être mieux symbolisée que par l’englobement matériel de la future Ève dans le corps du premier Adam, alors c’était depuis le mythe adamique que nous devions apporter cette correction. Selon Dumont, Adam, ou dans notre langue l’homme, est deux choses à la fois: le représentant de l’espèce humaine et le prototype mâle de cette espèce. À un premier plan homme et femme sont identiques, à un second niveau la femme est l’opposé ou le contraire de l’homme. Il nous a fallu du temps pour comprendre ce qu’étaient « opposé » et « contraire », ce qui les différenciait et par la même les distinguait, et ce ne sont pas les définitions des dictionnaires qui nous auront facilité la tache. </p>
                          <p>Mais lorsque pour définir l’une, on ne renvoie plus à l’autre, alors on finit par admettre que si nous semblions tourné dos à dos à un « contraire », nous paraissions face à face avec un « opposé ». Nous convenions donc que si depuis une ressemblance dans la différence nous étions intimement liés à un « contraire », nous étions en revanche liés dans l’intimité à un « opposé » à partir d’une différence dans la ressemblance. Mais pour commencer qui était donc ce contraire du représentant mâle de l’espèce humaine avec qui l’homme serait intimement lié? Dans la perspective d’une ressemblance dans la différence, il paraissait opportun de porter notre regard du côté de notre espèce et de son évolution. Si nous devions ainsi nous attarder sur l’odyssée des hominidés alors nul doute que le contraire de l’homme ne pouvait être qu’un de ses cousins, donc pour le moins un primate. </p>
                          <p>Ainsi, le contraire de anthrôpos, ce « visage d’homme » serait donc simus soit un « (animal) semblable à l’homme ». À l’humain mâle se contrarierait donc un singe mâle, puisque si cette proximité incitait à leur rapprochement, cette frappante ressemblance semblait à jamais les éloigner. Depuis la différence dans la ressemblance, nous posions que si la contrariété était d’« espèce », alors l’opposition serait de « genre », déduisant par la même que l’opposé d’un singe mâle n’était autre qu’un singe femelle. Ainsi le contraire de Adam, « représentant mâle de l’espèce humaine », était donc un mâle simiesque et l’opposé de ce représentant mâle, une femelle. Logiquement si Ève était à la fois le contraire et l’opposé de Adam, alors si Ève était bien un être féminin, elle n’était pas une femme mais un « singe femelle ».</p>
                          <p>Ève, un singe femelle? Sinon le phallocratisme outrancier de la Genèse, la chute peut paraître particulièrement inconvenant de misogynie… Pour autant et toujours selon Dumont, Ève serait le contraire ou l’opposé de Adam. Cependant et par définition, on ne peut pas être l’un ou l’autre, on est soit l’un soit l’autre, à la rigueur on peut être l’un et l’autre lorsque l’on est l’un puis l’autre. Mais, être « l’un et l’autre » ce n’est pas être le contraire et l’opposé de quelque chose, être l’un et l’autre, c’est être son « inverse ». Ici et ainsi commence le mythe de l’Inversion.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br>
        <br>
    </main>
<?php
//Appel template footer
require_once("./templates/footer.php");
?>
